apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeforge-system

resources:
  - project.yaml
  - application.yaml

labels:
  - pairs:
      app.kubernetes.io/name: platform-operator
      app.kubernetes.io/managed-by: kustomize