apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.service.port }}
  selector:
    {{- include "platform-operator.selectorLabels" . | nindent 4 }}